import Head from "next/head";
import ProgressBar from "../../components/Progress/ProgressBar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight, faSearch } from "@fortawesome/free-solid-svg-icons";
import TransactionCard from "../../components/TransactionCard";
import Button from "../../components/Button";
import {
  LineChart,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Line,
  Tooltip,
} from "recharts";
import colors from "../../utils/colors";
import Card from "../../components/Card";

const dummyData = [
  {
    name: "Jan",
    amt: 2400,
  },
  {
    name: "Feb",
    amt: 2210,
  },
  {
    name: "Mar",
    amt: 2290,
  },
  {
    name: "Apr",
    amt: 2000,
  },
  {
    name: "May",
    amt: 2181,
  },
  {
    name: "Jun",
    amt: 2500,
  },
  {
    name: "Jul",
    amt: 2100,
  },
];

function TransactionInput(props: { dollars: number; cents: number }) {
  return (
    <>
      <div className="transaction-wrapper">
        <div className="currency">$</div>
        <div className="dollars">{props.dollars}</div>
        <div className="cents">{props.cents}</div>
      </div>
      <style jsx>{`
        .transaction-wrapper {
          font-size: 4rem;
          display: flex;
          font-weight: 700;
          display: flex;
        }
        .currency {
          margin-right: 8px;
        }
        .cents {
          font-size: 2rem;
          align-self: flex-start;
        }
      `}</style>
    </>
  );
}

function Label() {
  return (
    <>
      <Head>
        <title>Label 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>Label 1</h1>
          <div className="primaryContainer">
            <div className="cardContainer">
              <div className="progressWrapper">
                <div className="stats">
                  <div>
                    <span className="button-like">Spent today:</span>
                    <span className="value button-like">$53</span>
                  </div>
                  <div>
                    <span className="button-like">transactions today:</span>
                    <span className="value button-like">03</span>
                  </div>
                  <div>
                    <span className="button-like">spent this week:</span>
                    <span className="value button-like">$93</span>
                  </div>
                  <div>
                    <span className="button-like">
                      transactions this week:
                    </span>
                    <span className="value button-like">12</span>
                  </div>
                  <div>
                    <span className="button-like">spent this month:</span>
                    <span className="value button-like">$153</span>
                  </div>
                  <div>
                    <span className="button-like">
                      transactions this month:
                    </span>
                    <span className="value button-like">37</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="search">
              <FontAwesomeIcon icon={faSearch} strokeWidth={1} />
              <input placeholder="Search..." />
            </div>
          </div>
        </div>
        <div className="section">
          <h2>Statistics</h2>
          <div className="cardGrid">
            <div>
              <h3>Weekly Transactions</h3>
              <LineChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Line type="monotone" dataKey="amt" stroke={colors.primary} />
              </LineChart>
            </div>
            <div>
              <h3>Monthly Transactions</h3>
              <LineChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Line type="monotone" dataKey="amt" stroke={colors.primary} />
              </LineChart>
            </div>

            <div>
              <h3>Average Weekly Spent</h3>
              <LineChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Line type="monotone" dataKey="amt" stroke={colors.primary} />
              </LineChart>
            </div>
            <div>
              <h3>Average Monthly Spent</h3>
              <LineChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Line type="monotone" dataKey="amt" stroke={colors.primary} />
              </LineChart>
            </div>
          </div>
          <div>
            <h2>Recent Transactions</h2>
            <div className="horizontalGrid">
              <div className="horizontalGridWrapper">
                <TransactionCard
                  title="Activity 1"
                  description="Some description for activity 1"
                  value={-70}
                />
                <TransactionCard
                  title="Activity 2"
                  description="Some description for activity 2"
                  value={-7}
                />
                <TransactionCard
                  title="Activity 3"
                  description="Some description for activity 3"
                  value={50}
                />
                <TransactionCard
                  title="Activity 4"
                  description="Some description for activity 4"
                  value={23}
                />
                <TransactionCard
                  title="Activity 5"
                  description="Some description for activity 5"
                  value={-45}
                />
                <TransactionCard
                  title="Activity 5"
                  description="Some description for activity 5"
                  value={-7.99}
                />
                <TransactionCard
                  title="Activity 6"
                  description="Some description for activity 6"
                  value={89}
                />
              </div>
            </div>
            <div style={{ float: "right" }}>
              <Button secondary small endIcon={faAngleRight}>
                View all
              </Button>
            </div>
          </div>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />

      <style jsx>
        {`
          main {
            padding: 12px;
          }
          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
          }

          .mainWrapper {
            width: 100%;
            align-items: center;
          }

          .mainWrapper h1,
          .mainWrapper .primaryContainer {
            flex-basis: 50%;
            justify-content: center;
            align-self: center;
          }

          .primaryContainer {
            max-width: 500px;
            display: flex;
            flex-direction: column;
          }
          .cardContainer {
            padding: 16px;
            border-radius: 16px;
          }

          .progressWrapper {
            justify-content: space-between;
          }

          .search {
            width: 100%;
            padding: 0px 16px;
            border-radius: 12px;
            background: rgba(255, 255, 255, 0.05);
            margin-top: 8px;
          }

          .search input {
            margin-left: 8px;
            padding: 12px 8px;
            background: transparent;
            border: none;
            width: 80%;
            color: #fff8;
          }

          .search input:hover,
          .search input:focus {
            outline: none;
          }

          .search svg {
            stroke-width: 1px;
          }

          .mainWrapper,
          .progressWrapper {
            display: flex;
          }
          .progressWrapper {
            flex-direction: column;
            align-items: center;
            justify-content: center;
          }

          .cardGrid {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-between;
          }

          .cardGrid h3 {
            text-align: center;
            font-size: 12px;
            text-transform: uppercase;
            font-weight: 900;
          }
          .stats {
            width: 100%;
            margin-top: 32px;
          }
          .button-like {
            text-transform: uppercase;
            letter-spacing: 1px;
            font-weight: 900;
            font-size: 12px;
          }

          .value {
            color: rgba(255, 255, 255, 0.7);
            float: right;
          }

          .horizontalGrid {
            max-width: 100vw;
            overflow-x: auto;
          }
          .horizontalGridWrapper {
            width: max-content;
            display: flex;
          }
          h2 {
            margin-left: 12px;
          }
          .section {
          }

          @media (max-width: 850px) {
            .mainWrapper {
              flex-direction: column;
            }
          }

          @media (max-width: 500px) {
            .mainWrapper {
              margin-top: 32px;
            }
            .progressWrapper > :global(.progressContainer) {
              margin: 6px;
            }

            :global(.progressBar) {
              width: 30px !important;
              border-radius: 8px !important;
            }
            :global(.progressElement) {
              width: 24px !important;
              border-radius: 6px !important;
            }
            .cardContainer {
              padding: 8px;
              border-radius: 8px;
            }
            h1 {
              font-size: 3rem;
            }
          }
        `}
      </style>
    </>
  );
}

export default Label;
