import Head from "next/head";
import ProgressBar from "../../components/Progress/ProgressBar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight, faSearch } from "@fortawesome/free-solid-svg-icons";
import LabelCard from "../../components/LabelCard";
import { PieChart, Pie, Cell, Tooltip } from "recharts";

const data01 = [
  {
    name: "Group A",
    value: 400,
  },
  {
    name: "Group B",
    value: 300,
  },
  {
    name: "Group C",
    value: 300,
  },
  {
    name: "Group D",
    value: 200,
  },
  {
    name: "Group E",
    value: 278,
  },
  {
    name: "Group F",
    value: 189,
  },
];

function Wallets() {
  return (
    <>
      <Head>
        <title>My Labels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>My Labels</h1>
          <div className="primaryContainer">
            <div className="cardContainer">
              <PieChart width={300} height={300}>
                <Pie
                  data={data01}
                  dataKey="value"
                  nameKey="name"
                  cx="50%"
                  cy="50%"
                  innerRadius={80}
                  outerRadius={100}
                  fill="#8884d8"
                  strokeWidth="2px"
                  stroke="#121212"
                  label
                >
                  {data01.map((entry, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={
                        [
                          "#6bc4abc7",
                          "#6b8ac4c7",
                          "#a46bc4c7",
                          "#c4be6bc7",
                          "#a46bc4c7",
                        ][Math.floor(Math.random() * 4)]
                      }
                    />
                  ))}
                </Pie>
              </PieChart>
            </div>
            <div className="search">
              <FontAwesomeIcon icon={faSearch} strokeWidth={1} />
              <input placeholder="Search..." />
            </div>
          </div>
        </div>
        <div className="section">
          <div className="cardGrid">
            <LabelCard
              title="Label 1"
              description="Some description for Label 1"
              value={70}
            />
            <LabelCard
              title="Label 2"
              description="Some description for Label 2"
              value={7}
            />
            <LabelCard
              title="Label 3"
              description="Some description for Label 3"
              value={50}
            />
          </div>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />

      <style jsx>
        {`
          main {
            padding: 12px;
          }

          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
          }

          .mainWrapper {
            width: 100%;
            align-items: center;
          }

          .mainWrapper h1,
          .mainWrapper .primaryContainer {
            flex-basis: 50%;
            justify-content: center;
            align-self: center;
          }

          .primaryContainer {
            max-width: 500px;
            display: flex;
            flex-direction: column;
          }
          .cardContainer {
            padding: 16px;
            border-radius: 16px;
            display: flex;
            align-items: center;
            justify-content: center;
          }

          .progressWrapper {
            justify-content: space-between;
          }

          .search {
            width: 100%;
            padding: 0px 16px;
            border-radius: 12px;
            background: rgba(255, 255, 255, 0.05);
            margin-top: 8px;
          }

          .search input {
            margin-left: 8px;
            padding: 12px 8px;
            background: transparent;
            border: none;
            width: 80%;
            color: #fff8;
          }

          .search input:hover,
          .search input:focus {
            outline: none;
          }

          .search svg {
            stroke-width: 1px;
          }

          .mainWrapper,
          .progressWrapper {
            display: flex;
          }

          .cardGrid {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-evenly;
          }
          .section {
            margin-top: 32px;
          }
          @media (max-width: 850px) {
            .mainWrapper {
              flex-direction: column;
            }
          }

          @media (max-width: 500px) {
            .mainWrapper {
              margin-top: 32px;
            }
          }
        `}
      </style>
    </>
  );
}

export default Wallets;
