import Head from "next/head";
import ProgressBar from "../../components/Progress/ProgressBar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight, faSearch } from "@fortawesome/free-solid-svg-icons";
import TransactionCard from "../../components/TransactionCard";
import Button from "../../components/Button";
import {
  LineChart,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Line,
  Tooltip,
} from "recharts";
import colors from "../../utils/colors";
import Card from "../../components/Card";

const dummyData = [
  {
    name: "Jan",
    amt: 2400,
  },
  {
    name: "Feb",
    amt: 2210,
  },
  {
    name: "Mar",
    amt: 2290,
  },
  {
    name: "Apr",
    amt: 2000,
  },
  {
    name: "May",
    amt: 2181,
  },
  {
    name: "Jun",
    amt: 2500,
  },
  {
    name: "Jul",
    amt: 2100,
  },
];

function Wallet() {
  return (
    <>
      <Head>
        <title>Wallet 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>Wallet 1</h1>
        </div>
        <div className="section">
          <div>
            <h2>Recent Transactions</h2>
            <div className="horizontalGrid">
              <div className="horizontalGridWrapper">
                <TransactionCard
                  title="Activity 1"
                  description="Some description for activity 1"
                  value={-70}
                />
                <TransactionCard
                  title="Activity 2"
                  description="Some description for activity 2"
                  value={-7}
                />
                <TransactionCard
                  title="Activity 3"
                  description="Some description for activity 3"
                  value={50}
                />
                <TransactionCard
                  title="Activity 4"
                  description="Some description for activity 4"
                  value={23}
                />
                <TransactionCard
                  title="Activity 5"
                  description="Some description for activity 5"
                  value={-45}
                />
                <TransactionCard
                  title="Activity 5"
                  description="Some description for activity 5"
                  value={-7.99}
                />
                <TransactionCard
                  title="Activity 6"
                  description="Some description for activity 6"
                  value={89}
                />
              </div>
            </div>
            <div style={{ float: "right" }}>
              <Button secondary small endIcon={faAngleRight}>
                View all
              </Button>
            </div>
          </div>
          <h2>Statistics</h2>
          <div className="cardGrid">
            <Card small backgroundColor="rgba(255, 255, 255, 0.01)">
              <h3>Average Monthly balance</h3>
              <AreaChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 10, right: 30, left: 0, bottom: 0 }}
              >
                <defs>
                  <linearGradient id="colorAmt" x1="0" y1="0" x2="0" y2="1">
                    <stop
                      offset="5%"
                      stopColor={colors.primary}
                      stopOpacity={0.8}
                    />
                    <stop
                      offset="95%"
                      stopColor={colors.primary}
                      stopOpacity={0}
                    />
                  </linearGradient>
                </defs>
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Area
                  type="monotone"
                  dataKey="amt"
                  stroke={colors.primary}
                  fillOpacity={1}
                  fill="url(#colorAmt)"
                />
              </AreaChart>
            </Card>
            <Card small backgroundColor="rgba(255, 255, 255, 0.01)">
              <h3>Average Weekly balance</h3>
              <LineChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Line type="monotone" dataKey="amt" stroke={colors.primary} />
              </LineChart>
            </Card>

            <Card small backgroundColor="rgba(255, 255, 255, 0.01)">
              <h3>Average Monthly Spend</h3>
              <AreaChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 10, right: 30, left: 0, bottom: 0 }}
              >
                <defs>
                  <linearGradient id="colorAmt" x1="0" y1="0" x2="0" y2="1">
                    <stop
                      offset="5%"
                      stopColor={colors.primary}
                      stopOpacity={0.8}
                    />
                    <stop
                      offset="95%"
                      stopColor={colors.primary}
                      stopOpacity={0}
                    />
                  </linearGradient>
                </defs>
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Area
                  type="monotone"
                  dataKey="amt"
                  stroke={colors.primary}
                  fillOpacity={1}
                  fill="url(#colorAmt)"
                />
              </AreaChart>
            </Card>
            <Card small backgroundColor="rgba(255, 255, 255, 0.01)">
              <h3>Average Weekly Spend</h3>
              <LineChart
                width={300}
                height={200}
                data={dummyData}
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip
                  wrapperStyle={{ borderRadius: "8px" }}
                  contentStyle={{
                    background: "#000",
                    borderRadius: "16px",
                    border: "none",
                  }}
                />
                <Line type="monotone" dataKey="amt" stroke={colors.primary} />
              </LineChart>
            </Card>
          </div>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />

      <style jsx>
        {`
          main {
            padding: 12px;
          }

          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
          }
          .mainWrapper {
            width: 100%;
            align-items: center;
            display: flex;
            justify-content: center;
          }

          .mainWrapper h1 {
            justify-content: center;
            align-self: center;
          }

          .cardGrid {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-evenly;
          }
          .horizontalGrid {
            max-width: 100vw;
            overflow-x: auto;
          }
          .horizontalGridWrapper {
            width: max-content;
            display: flex;
          }
          h2 {
            margin-left: 12px;
          }
          .section {
          }

          @media (max-width: 850px) {
            .mainWrapper {
              flex-direction: column;
            }
          }

          @media (max-width: 500px) {
            .mainWrapper {
              margin-top: 32px;
            }
            .progressWrapper > :global(.progressContainer) {
              margin: 6px;
            }

            :global(.progressBar) {
              width: 30px !important;
              border-radius: 8px !important;
            }
            :global(.progressElement) {
              width: 24px !important;
              border-radius: 6px !important;
            }
            .cardContainer {
              padding: 8px;
              border-radius: 8px;
            }
            h1 {
              font-size: 3rem;
            }
          }
        `}
      </style>
      {/* display: grid;
            grid-template-columns: 28vw 28vw 28vw;
            padding: 0 24px;
            margin-top: 24px; */}
    </>
  );
}

export default Wallet;
