import Head from "next/head";
import { faAdd } from "@fortawesome/free-solid-svg-icons";
import WalletCard from "../../components/WalletCard";
import Button from "../../components/Button";
import Router from "next/router";
import { useAppDispatch, useAppSelector } from "../../utils/reduxHooks";
import { useEffect, useState } from "react";
import { WalletType } from "../../utils/types";
import URLs, { API_BASE } from "../../utils/endpoints";
import { hideGlobalLoader, showGlobalLoader } from "../../components/GlobalLoader/loaderSlice";

function Wallets() {
  const dispatch = useAppDispatch();
  const auth = useAppSelector((state) => state.auth);

  const [wallets, setWallets] = useState<WalletType[]>([])
 
  useEffect(() => {
    dispatch(showGlobalLoader())
    fetch(API_BASE + URLs.WALLET.GET,
      {
        headers: {
          Authorization: "Token " + auth.token,
        },
    }).then(res => res.json()).then(res => {
      dispatch(hideGlobalLoader())
      setWallets(res.wallets);
    })
  }, [auth, dispatch]);
  return (
    <>
      <Head>
        <title>My Wallets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>My Wallets</h1>

          <Button startIcon={faAdd} fullRadius>
            Create New
          </Button>
        </div>
        <div className="section">
          <div className="cardGrid">
            {
              wallets.length !== 0 && wallets.map(elem => <WalletCard
                data={elem}
                key={elem.id}
                onClick={() => Router.push("/wallets/" + elem.id)}
              />)
            }
          </div>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />

      <style jsx>
        {`
          main {
            padding: 12px;
          }

          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
            margin-bottom: 16px;
          }

          .mainWrapper {
            width: 100%;
            align-items: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-bottom: 32px;
          }

          .search {
            width: 100%;
            padding: 0px 16px;
            border-radius: 12px;
            background: rgba(255, 255, 255, 0.05);
            margin-top: 8px;
          }

          .search input {
            margin-left: 8px;
            padding: 12px 8px;
            background: transparent;
            border: none;
            width: 80%;
            color: #fff8;
          }

          .search input:hover,
          .search input:focus {
            outline: none;
          }

          .search svg {
            stroke-width: 1px;
          }
          .cardGrid {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-evenly;
          }
          @media (max-width: 500px) {
            .mainWrapper {
              margin-top: 32px;
            }
          }
        `}
      </style>
    </>
  );
}

export default Wallets;
