import React from "react";
import Head from "next/head";
import { faMoneyBillTransfer } from "@fortawesome/free-solid-svg-icons";
import Button from "../components/Button";
import Input from "../components/Input";
import Label from "../components/Label";
import WalletCard from "../components/WalletCard";
import Card from "../components/Card";

function TransactionInput() {
  const dollars = React.useRef<HTMLDivElement>(null);
  const cents = React.useRef<HTMLDivElement>(null);

  const handleDollarChange = () => {
    if (dollars.current) {
      const val = Number(dollars.current.innerText);
      if (val === 0 || val === NaN) {
        dollars.current.innerText = "00";
        dollars.current.style.opacity = "0.1";
      } else {
        dollars.current.style.opacity = "1";
      }
    }
  };
  const handleCentChange = () => {
    if (cents.current) {
      const val = Number(cents.current.innerText);
      if (val === 0 || val === NaN) {
        cents.current.innerText = "00";
        cents.current.style.opacity = "0.1";
      } else {
        cents.current.style.opacity = "1";
      }
    }
  };
  return (
    <>
      <div className="transaction-wrapper">
        <div className="currency">$</div>
        <div
          className="dollars"
          contentEditable
          ref={dollars}
          onKeyUp={handleDollarChange}
        >
          00
        </div>
        <div
          className="cents"
          contentEditable
          ref={cents}
          onKeyUp={handleCentChange}
        >
          00
        </div>
      </div>
      <style jsx>{`
        .transaction-wrapper {
          font-size: 4rem;
          display: flex;
          font-weight: 700;
          display: flex;
        }
        .currency {
          margin-right: 8px;
        }
        .cents {
          font-size: 2rem;
          align-self: flex-start;
        }
        .dollars,
        .cents {
          opacity: 0.1;
        }
        .dollars:focus,
        .cents:focus {
          outline: none;
        }
      `}</style>
    </>
  );
}

function Add() {
  return (
    <>
      <Head>
        <title>Add</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>Add</h1>
        </div>
        <div className="section">
          <h3>Transaction Amount</h3>
          <TransactionInput />
          <Input type="text" placeholder="Description" />
          <h3>Pick labels:</h3>
          <div>
            <Label>Food</Label>
            <Label>Stationary</Label>
            <Label>Bill</Label>
          </div>
          <h3>Which wallet to use?</h3>
          <div className="cardGrid">
            <WalletCard
              small
              title="Wallet 1"
              description="Some description for Wallet 1"
              value={70}
              selected
            />
            <WalletCard
              small
              title="Wallet 2"
              description="Some description for Wallet 2"
              value={7}
            />
            <WalletCard
              small
              title="Wallet 3"
              description="Some description for Wallet 3"
              value={50}
            />
          </div>
          <h3>Is this an expense or an income?</h3>
          <div className="cardGrid">
            <Card small backgroundColor="#6bc479c7">
              <h3>Income</h3>
            </Card>
            <Card small backgroundColor="#f44336c7">
              <h3>Expense</h3>
            </Card>
          </div>
          <Button startIcon={faMoneyBillTransfer}>Add transaction</Button>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />

      <style jsx>
        {`
          main {
            padding: 12px;
          }

          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
          }
          .cardGrid h3 {
            margin: 12px;
          }

          .mainWrapper {
            width: 100%;
            align-items: center;
            display: flex;
            justify-content: center;
          }

          .mainWrapper h1 {
            justify-content: center;
            align-self: center;
          }

          .cardGrid {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: center;
          }
          .section {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
          }

          @media (max-width: 500px) {
            .mainWrapper {
              margin-top: 32px;
            }
            h1 {
              font-size: 3rem;
            }
          }
        `}
      </style>
    </>
  );
}

export default Add;
