import Head from "next/head";
import dynamic from 'next/dynamic'

const PerfProgress = dynamic(() => import('../components/performanceProgress'), {
  ssr: false,
})

function Performance() {
  return (
    <>
      <Head>
        <title>Perform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="perfProgress">
        <PerfProgress />
        </div>
      </main>

      <style jsx>
        {`
        .perfProgress {
            top: 50%;
            left: 50%;
            position: fixed;
            transform: translateY(-50%);
        }
        `}
      </style>
    </>
  );
}

export default Performance;