import React from "react";
import Head from "next/head";
import Label from "../components/Label";
import Card from "../components/Card";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSearch } from "@fortawesome/free-solid-svg-icons";

function Transaction(props: {
  title: string;
  description?: string;
  value: number;
  labels?: Array<string>;
}) {
  return (
    <Card extraStyles="width: 100%;max-width: 700px;">
      <div className="wrapper">
        <div className="content">
          <h3>{props.title}</h3>
          <p style={{ color: "#fff6" }}>{props.description}</p>
          <div>
            {props.labels &&
              props.labels.map((label, index) => (
                <Label key={index}>{label}</Label>
              ))}
          </div>
          <div className="details">
            <span>12 Nov 22</span>
            <span>•</span>
            <span>Wallet 1</span>
          </div>
        </div>
        <h1>${props.value}</h1>
      </div>
      <style jsx>{`
        .wrapper {
          display: flex;
          align-items: center;
        }
        h3,
        p {
          margin: 4px 0;
        }
        .content {
          margin-right: 16px;
          flex-grow: 1;
        }
        .details {
          font-size: small;
          color: #fff6;
        }
        .details span {
          margin: 0 2px;
        }
      `}</style>
    </Card>
  );
}

function TransactionHistory() {
  return (
    <>
      <Head>
        <title>Transaction History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>Transaction History</h1>
        </div>
        <div className="section">
          <div className="filters">
            <div className="search">
              <FontAwesomeIcon icon={faSearch} strokeWidth={1} />
              <input placeholder="Search..." />
            </div>
            <h4>Filter by labels</h4>
            <div className="horizontalScroll">
              <Label>Food</Label>
              <Label>Stationary</Label>
              <Label>Bills</Label>
            </div>
            <h4>Filter by wallet</h4>
            <div className="horizontalScroll">
              <Label>Wallet 1</Label>
              <Label>Wallet 2</Label>
              <Label>Wallet 3</Label>
              <Label>Wallet 4</Label>
            </div>
          </div>
          <div className="trxns cardGrid">
            <h4>5 Transaction(s)</h4>
            <Transaction title="trxn 1" value={45} />
            <Transaction
              title="trxn 2"
              value={65}
              description="some great description"
              labels={["food", "dfc", "food", "dfc", "food", "dfc"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              description="some great description"
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              description="some great description"
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              description="some great description"
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              labels={["stationary", "book"]}
            />
            <Transaction
              title="trxn 3"
              value={15}
              description="some great description"
              labels={["stationary", "book"]}
            />
          </div>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />

      <style jsx>
        {`
          main {
            padding: 12px;
          }

          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
          }
          .cardGrid h4 {
            margin: 8px 16px;
          }

          .mainWrapper {
            width: 100%;
            align-items: center;
            display: flex;
            justify-content: center;
          }

          .mainWrapper h1 {
            justify-content: center;
            align-self: center;
          }
          .search {
            width: 100%;
            padding: 0px 16px;
            border-radius: 12px;
            background: rgba(255, 255, 255, 0.05);
            margin-top: 8px;
          }

          .search input {
            margin-left: 8px;
            padding: 12px 8px;
            background: transparent;
            border: none;
            width: 80%;
            color: #fff8;
          }

          .search input:hover,
          .search input:focus {
            outline: none;
          }

          .search svg {
            stroke-width: 1px;
          }

          .cardGrid {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            max-width: 724px;
          }
          .section {
            display: flex;
            justify-content: center;
          }
          .filters {
            padding: 12px 24px;
            border-radius: 12px;
            background: rgba(255, 255, 255, 0.05);
            height: fit-content;
            flex-grow: 0;
            margin-top: 8px;
            min-width: max-content;
          }
          .filters h4 {
            text-transform: uppercase;
            font-weight: 700;
            font-size: 12px;
          }
          @media (max-width: 500px) {
            .mainWrapper {
              margin-top: 32px;
            }
            h1 {
              font-size: 3rem;
            }
          }

          @media (max-width: 950px) {
            .section {
              flex-direction: column;
              align-items: center;
            }
            .filters {
              width: 700px;
              margin: 8px;
            }
          }
          @media (max-width: 700px) {
            .filters {
              min-width: auto;
              width: calc(100% - 24px);
            }
          }
        `}
      </style>
    </>
  );
}

export default TransactionHistory;
