import Head from "next/head";
import { faSignOut } from "@fortawesome/free-solid-svg-icons";
import Button from "../components/Button";
import { useAppDispatch, useAppSelector } from "../utils/reduxHooks";
import Navbar from "../components/Navbar";
import { logout } from "../utils/authThunk";
import { useEffect } from "react";
import Router from "next/router";
import { showSnackbarThunk } from "../components/Snackbar/snackbarThunk";

function Wallets() {
  const dispatch = useAppDispatch();
  const user = useAppSelector((state) => state.auth);
  const labels = useAppSelector((state) => state.labels.labels.length);
  const wallets = useAppSelector((state) => state.wallets.wallets.length);
  useEffect(() => {
    if (!user.token) {
      Router.push("/login");
      dispatch(showSnackbarThunk("Please login before accessing this page"));
    }
  }, [user.token, dispatch]);
  return (
    <>
      <Head>
        <title>
          {user.user_data?.first_name + " " + user.user_data?.last_name}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mainWrapper">
          <h1>
            {user.user_data?.first_name + " " + user.user_data?.last_name}
          </h1>
          <Button
            startIcon={faSignOut}
            secondary
            onClick={() => dispatch(logout())}
          >
            Log out
          </Button>
        </div>
        <div className="data">
          <div className="stats">
            <div className="entry vertical">
              <div className="button-like">Email</div>
              <div className="value button-like">
                {user.user_data?.email || "No email connected"}
              </div>
            </div>
            <div className="entry vertical">
              <div className="button-like">Username</div>
              <div className="value button-like">
                {user.user_data?.username || "No email connected"}
              </div>
            </div>
            <div className="entry horizontal">
              <span className="value button-like">{labels}</span>
              <span className="button-like">Labels</span>
            </div>
            <div className="entry horizontal">
              <span className="value button-like">{wallets}</span>
              <span className="button-like">wallets</span>
            </div>
          </div>
        </div>
      </main>
      <div style={{ width: "100vw", height: "72px" }} />
      <Navbar />

      <style jsx>
        {`
          main {
            padding: 12px;
          }

          h1 {
            font-weight: 700;
            color: white;
            font-size: 4rem;
            text-align: center;
            margin-bottom: 16px;
          }

          .mainWrapper {
            width: 100%;
            align-items: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-bottom: 32px;
          }

          .stats {
            margin-top: 32px;
          }
          .button-like {
            text-transform: uppercase;
            letter-spacing: 1px;
            font-weight: 900;
            font-size: 12px;
            color: rgba(255, 255, 255, 0.7);
          }

          .value {
            color: rgba(255, 255, 255);
            font-size: 20px;
          }
          .entry {
            align-items: center;
            justify-content: center;
            margin-top: 12px;
          }
          .vertical .value {
            margin: 0;
          }
          .horizontal .value {
            margin: 0 8px;
          }
          .data {
            width: 100%;
            text-align: center;
          }
        `}
      </style>
    </>
  );
}

export default Wallets;
